CREATE DATABASE IF NOT EXISTS $DB_NAME DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci; \
CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD'; \
GRANT ALL ON $DB_NAME.* TO '$DB_USER'@'%'; \
FLUSH PRIVILEGES; \