#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER";
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

EOSQL


# psql -v
# ON_ERROR_STOP=1
# --username "$POSTGRES_USER"
# --dbname "$POSTGRES_DB" <<-EOSQL
# CREATE USER "$POSTGRES_USER";
# CREATE DATABASE "$POSTGRES_DB" ENCODING UTF8;
# GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER";
# CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

# ALTER USER "$POSTGRES_USER" WITH PASSWORD "$POSTGRES_PASSWORD";
# ALTER USER "$POSTGRES_USER" WITH SUPERUSER;
# EOSQL
