version: '3'

services:
    mariadb_service:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        expose:
            - "3306"
        networks:
            - inception_net
        volumes:
            - db_vol:/var/lib/mysql/
        env_file: .env

    nginx_service:
        container_name: nginx
        build: ./requirements/nginx/
        restart: always
        ports:
            - "443:443"
        volumes:
            - wp_vol:/var/www/
        networks:
            - inception_net
        env_file: .env

    wordpress_service:
        container_name: wordpress
        build: ./requirements/wordpress
        depends_on:
            - mariadb_service
        restart: always
        volumes:
            - wp_vol:/var/www/
        networks:
            - inception_net
        env_file: .env

networks:
    inception_net:

volumes:
    wp_vol:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/Users/seungyel/data/wp'
    db_vol:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/Users/seungyel/data/db'