version: '3.3'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        # init: true
        restart: always
        networks:
            - inception_net
        volumes:
            - db_vol:/var/lib/mysql/
        tty: true
        env_file: .env

    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        # init: true
        restart: always
        tty: true
        ports:
            - "443:443"
        volumes:
            - wp_vol:/var/www/wordpress
        networks:
            - inception_net
        depends_on:
            - wordpress
        env_file: .env

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        # init: true
        depends_on:
            - mariadb
        restart: always
        tty: true
        volumes:
          - wp_vol:/var/www/wordpress
        networks:
            - inception_net
        env_file: .env

networks:
    inception_net:
      driver: bridge

volumes:
    wp_vol:
      driver: local
      # driver_opts:
        # type: 'none'
        # o: 'bind'
        # device: '/home/user/data/wp'
    db_vol:
      driver: local
      # driver_opts:
        # type: 'none'
        # o: 'bind'
        # device: '/home/user/data/db'