version: '3'
services:
  nginx:
      container_name: nginx
      image: "nginx:latest"
      ports:
       - "80:80"
      networks:
       - backend
 
networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge


version: "3.3"
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp-vol:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  mysql-vol: {}
  wp-vol: {}